### PR TITLE
Back out "metrics states vectorization"

### PR DESCRIPTION
**Pull request by xunnanxu**
Differential Revision: D42706482

### CODE REVIEW

**Review by xw285cornell — APPROVED** [review]

**Review by xw285cornell — APPROVED** [review]
LGTM, the original diff is causing checkpoint load numerical problems

**Comment by xw285cornell** [comment]
cc oncall @dstaay-fb

**Comment by dstaay-fb** [comment]
Imported already by facebook-github-bot; this should have been auto-closed, doing it manually.

**Pull request closed without merging**
