### PR TITLE
[tde] Migrate naive id transformer

### PR DESCRIPTION
**Pull request by zhuzilin**
This PR is trying to migrate `NaiveIDTransformer` to the top folder. The idea behind the naive transformer is quite simple, we use a hash map (`ska::flat_hash_map`) to store the global id to cache id map, and use a bitmap to record the empty slot in the cache.

cc @reyoung

### CODE REVIEW

**Comment by zhuzilin** [comment]
gently ping @colin2328 @divchenko

**Comment by colin2328** [comment]
looks fine to me. @IvanKobzarev any thoughts on style?

**Comment by colin2328** [comment]
@zhuzilin  -> which object will use NaiveIDTransformer (python wrapper) as state? will it live on each trainer? (and each trainer will have the mapping?) cc @divchenko

**Comment by zhuzilin** [comment]
> @zhuzilin -> which object will use NaiveIDTransformer (python wrapper) as state? will it live on each trainer? (and each trainer will have the mapping?) cc @divchenko

Currently we only need an id transformer on rank 0, and global ids on all ranks will be gathered to rank 0.

**Comment by colin2328** [comment]
@zhuzilin  I see, and all ofthis will be done in the prefetching stage of the train_pipeline?

**Comment by zhuzilin** [comment]
> @zhuzilin I see, and all ofthis will be done in the prefetching stage of the train_pipeline?

yes, exactly.

**Review by colin2328 — APPROVED** [review]
LGTM thanks

**Pull request closed without merging**
